export const PATH = {
  AUTH_ROOT: "/auth",
  AUTH_LOGIN: "/",
  // AUTH_SIGNUP: "/auth/signup",

  // 학생
  STUDENT_ROOT: "/student",
  STUDENT_COMMUNITY: "/student/community",
  STUDENT_COMMUNITY_ANNOUNCEMENTS: "/student/community/announcements",
  STUDENT_PRODUCTS: "/student/products",
  STUDENT_ORDERS: "/student/orders",
  STUDENT_ORDERS_ENTRY: "/student/orders/entry",
  STUDENT_ORDERS_LIST: "/student/orders/list",
  STUDENT_ORDERS_HISTORY: "/student/orders/history",
  STUDENT_LOUNGE: "/student/studentLounge",
  STUDENT_LOUNGE_DASHBOARD: "/student/studentLounge/dashboard",
  STUDENT_LOUNGE_MISSION: "/student/studentLounge/mission",
  STUDENT_LOUNGE_ANNOUNCEMENTS: "/student/studentLounge/announcements",
  STUDENT_LOUNGE_QNA: "/student/studentLounge/qna",
  STUDENT_LOUNGE_AI_ASSISTANT: "/student/studentLounge/ai-assistant",
  STUDENT_POINTS: "/student/points",
  STUDENT_POINTS_CHARGE: "/student/points/charge",
  STUDENT_POINTS_HISTORY: "/student/points/history",
  STUDENT_PROFILE: "/student/profile",
  STUDENT_LOUNGE_LIBRARY: "/student/studentLounge/library",
  // 어드민
  ADMIN_ROOT: "/admin",
  ADMIN_COMMUNITY: "/admin/community",
  ADMIN_COMMUNITY_ANNOUNCEMENTS: "/admin/community/announcements",
  ADMIN_COMMUNITY_NEWS: "/admin/community/news",
  ADMIN_COMMUNITY_BEFORE_AND_AFTER: "/admin/community/before-after",
  ADMIN_COHORT: "/admin/cohort",
  ADMIN_MISSIONS: "/admin/missions",
  ADMIN_MISSIONS_NOTICE: "/admin/missions/notice",
  ADMIN_COURSE: "/admin/course",
  ADMIN_REVIEW: "/admin/review",
  ADMIN_USER: "/admin/user",
  ADMIN_STUDENTS: "/admin/students",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_YOUTUBE_CHANNELS: "/admin/channels",
  ADMIN_YOUTUBE_VIDEOS: "/admin/videos",

  // 공통 마이페이지
  MY_PAGE: "/my-page",
};
